#NAME:Hun Lee
#EMAIL:ehtk0502@gmail.com
#ID:604958834

.SILENT:

default:

dist: default
	tar -czf lab4a-604958834.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
