#NAME: Hun Lee
#EMAIL: ehtk0502@gmail.com
#ID:604958834

.SILENT:

default:
	gcc -Wall -Wextra -o lab1a -g lab1a.c
dist: default
	tar -czf lab1a-604958834.tar.gz lab1a.c README Makefile
clean:
	rm -rf lab1a*.c*tar.gz
